export const gridState = {
  currentPage: 1,
  isLoading: false,
  isSearchMode: false,
  searchQuery: "",
  currentFilter: "popular",
  currentCategoryId: null,
  hasMore: true,
  renderVersion: 0,
  pendingInitialRender: false,
  discoverySnapshotId: null,
  discoveryController: null,
  featuredCandidates: [],
  featuredIds: new Set(),
  featuredEngineIds: new Set(),
  engineTooltip: null,
  engineTooltipGrid: null,
  status: "ready",
};
